#
# Makefile for the tablet drivers
#

# Multipart objects.

#obj-m	+= fpc102x.o
obj-$(CONFIG_INPUT_FPC102X_TOUCH)	+= fpc102x.o

fpc102x-objs := fpc1020_main.o fpc1020_common.o fpc1020_input_nav.o fpc1020_navlib.o fpc1020_capture.o fpc1020_regulator.o fpc1020_debug.o

